language: python
cache: pip
python:
- '2.7'
- '3.6'
- '3.8'
before_install:
- sudo apt-get install libcurl4-openssl-dev
install:
- make init;
- make install;
script:
- make test;

jobs:
  include:
    - stage: style-check
      python: 3.8
      script:
        - make style-check
        - make lint
